routes/web.php
<?php

use App\Http\Controllers\BudgetCategoryController;
use App\Http\Controllers\BudgetItemController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TaskController;
use App\Models\Task;
use App\Models\User;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\Rule;
use Illuminate\Auth\Events\Login;
use App\Http\Requests\TaskRequest;
use App\Models\BudgetCategory;
use App\Models\BudgetItem;
use Illuminate\Support\Facades\Route;
use League\CommonMark\Extension\DescriptionList\Node\Description;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
//INDEX
Route::fallback(function(){
  return view('404') ;
});
Route::get('/', function() {
  return redirect()->route('landing');
});
Route::view('/owedding','user.landing')
->name('landing');

Route::view('/budget', 'weddingBudget.budget')->name('budget');
//USER
Route::post('/login',[UserController::class,'login'])->name('users.login');
Route::get('/login',[UserController::class,'showlogin'])->name('users.showlogin');
Route::post('/logout',[UserController::class,'logout'])->name('users.logout');
Route::get('/register',[UserController::class,'showRegister'])->name('users.showRegister');
Route::post('/update-current-budget',[UserController::class,'updateCurrentBudget'])->name('users.updateCurrentBudget');
Route::resource('users',UserController::class)->only([
  'store'
]);
//BUDGET MANAGEMENT
Route::resource('budgetCategories', BudgetCategoryController::class)->only([
  'index','store', 'update', 'destroy'
]);
Route::resource('budgetItems', BudgetItemController::class)->only([
  'store', 'update', 'destroy'
]);

//TASK
Route::resource('tasks', TaskController::class);
Route::put('tasks/{task}/toggle-complete',[TaskController::class,'toggleComplete'])->name('tasks.toggleComplete');

resources/views/404.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,800;1,300;1,400;1,700&family=Sigmar+One&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="{{ asset('404page/reset.css') }}" />
    <link rel="stylesheet" href="{{ asset('404page/style.css') }}" />
  </head>
  <body>
    <div class="errorpage">
      <h1 class="errorpage-title">Oopps!</h1>
      <div class="errorpage-img">
        <img src="{{ asset('404page/coding.png') }}" alt="" />
      </div>
      <div class="errorpage-content">
        <h2 class="errorpage-content_top">PAGE NOT FOUND</h2>
        <h3 class="errorpage-content_sub">
          Sorry, the page you're looking for doesn't exist. <br />
          If you think somethin is broken,<br />
          report a problem.
        </h3>
      </div>
      <div class="errorpage-button">
        <button class="Button"><a href="{{ route('landing')}}">VỀ TRANG CHỦ</a></button>
      </div>
    </div>
  </body>
</html>

resources/views/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('form', ['task' => $task])
@endsection

resources/views/form.blade.php
@extends('layouts.app')

@section('title', isset($task) ? 'Edit task' : 'Add Task')

@section('content')
<form method="POST"
    action="{{ isset($task) ? route('tasks.update', ['task' => $task->id]) : route('tasks.store') }}">
        @csrf
        @isset($task)
            @method('PUT')
        @endisset
        <div>
            <label for="title">Title</label>
            <input text="text" name="title" id="title"
                   @class(['border-red-500' => $errors->has('title')])
                   value="{{ $task->title ?? old('title') }}" />
            @error('title')
                <p class="error">{{ $message }}</p>
            @enderror
        </div>
        <div>
            <label for="description">Description</label>
            <textarea name="description" id="description" rows="3"
                      @class(['border-red-500' => $errors->has('description')])>
                {{ $task->description ?? old('description') }}
            </textarea>
            @error('description')
                <p class="error">{{ $message }}</p>
            @enderror 
        </div>
        <div>
            <label for="Period">Period</label>
            <textarea name="period" id="period" rows="2"
                      @class(['border-red-500' => $errors->has('period')])>
                {{ $task->period ?? old('period') }}
            </textarea> 
            @error('period')
                <p class="error">{{ $message }}</p>
            @enderror
        </div>
        <div class="flex gap-2">
            <button class="btn" type="submit">
                @isset($task)
                    Update Task
                @else
                    Add Task
                @endisset
            </button>
            <a href="{{ route('tasks.index') }}" class="btn">
                Cancel
            </a>
        </div>
    </form>
@endsection

resources/views/show.blade.php
@extends('layouts.app')
@section('title', $task->title)


@section('content')
<p class="mb-4 text-slate-700">{{$task->description}}</p>

@if ($task->period)
    <p class="mb-4 text-slate-700">{{$task->period}}</p>
@endif

<p class="mb-4 text-sm text-slate-500">Created {{ $task->created_at->diffForHumans() }} • Updated
    {{ $task->updated_at->diffForHumans() }}</p>

<p class="mb-4">
    @if ($task->completed)
      <span class="font-medium text-green-500">completed</span>
    @else
      <span class="font-medium text-red-500">Not completed</span>
    @endif
  </p>

  <div class="flex gap-2">
    <form method="POST" action="{{ route('tasks.toggleComplete', ['task' => $task]) }}">
      @csrf
      @method('PUT')
      <button type="submit" class="btn">
        Mark as {{ $task->completed ? 'not completed' : 'completed' }}
      </button>
    </form>
  
    <a href="{{ route('tasks.edit',['task' =>$task]) }}"
       class="btn">
      Edit task
    </a>

    <form action="{{ route('tasks.destroy', ['task'=> $task]) }}" method="POST">
        @csrf
        @method('DELETE')
        <button type="submit" class="btn">Delete</button>
    </form>
</div>

@endsection