routes/web.php
<?php

use App\Http\Controllers\BudgetCategoryController;
use App\Http\Controllers\BudgetItemController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TaskController;
use App\Models\Task;
use App\Models\User;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\Rule;
use Illuminate\Auth\Events\Login;
use App\Http\Requests\TaskRequest;
use App\Models\BudgetCategory;
use App\Models\BudgetItem;
use Illuminate\Support\Facades\Route;
use League\CommonMark\Extension\DescriptionList\Node\Description;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
//INDEX
Route::fallback(function(){
  return view('404') ;
});
Route::get('/', function() {
  return redirect()->route('landing');
});
Route::view('/owedding','user.landing')
->name('landing');

Route::view('/budget', 'weddingBudget.budget')->name('budget');
//USER
Route::post('/login',[UserController::class,'login'])->name('users.login');
Route::get('/login',[UserController::class,'showlogin'])->name('users.showlogin');
Route::post('/logout',[UserController::class,'logout'])->name('users.logout');
Route::get('/register',[UserController::class,'showRegister'])->name('users.showRegister');
Route::post('/update-current-budget',[UserController::class,'updateCurrentBudget'])->name('users.updateCurrentBudget');
Route::resource('users',UserController::class)->only([
  'store'
]);
//BUDGET MANAGEMENT
Route::resource('budgetCategories', BudgetCategoryController::class)->only([
  'index','store', 'update', 'destroy'
]);
Route::resource('budgetItems', BudgetItemController::class)->only([
  'store', 'update', 'destroy'
]);

//TASK
Route::resource('tasks', TaskController::class);
Route::put('tasks/{task}/toggle-complete',[TaskController::class,'toggleComplete'])->name('tasks.toggleComplete');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    public function budgetCategory(){
        return $this->hasMany(BudgetCategory::class);
    }
    protected $fillable = [
        'name',
        'email',
        'password',
        'full_name',
        'phone_number',
        'birthday'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function tasks() {
        return $this->hasMany(Task::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Support\Str;

class UserController extends Controller
{
    /**
     * Display a listing of the resource (Profile).
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => ['required', 'min:3', 'max:10', Rule::unique('users', 'name')],
            'email' => ['required', 'email', Rule::unique('users', 'email')],
            'password' => ['required', 'min:8', 'max:200'],
            'retype_password' => ['required', 'same:password']
        ]);
        $user = new User;
        $user->name = $data['name'];
        $user->email = $data['email'];
        $user->email_verified_at = null;
        $user->password = bcrypt($data['password']);
        $user->current_budget = 0;
        $user->remember_token = Str::random(10);
        $user->save();
        $request->session()->put('user', $user);

        auth()->login($user);

        return redirect()->route('landing');
    }

    /**
     * Display the specified resource(này nếu làm admin chắc mới dùng).
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource(chỉnh profile).
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
    public function showLogin()
    {
        return view("user.signin");
    }
    public function login(Request $request)
    {
        $data = $request->validate([
            'loginemail' => 'required',
            'loginpassword' => 'required'
        ]);

        $credentials = ['email' => $data['loginemail'], 'password' => $data['loginpassword']];

        if (auth()->attempt($credentials)) {
            $request->session()->regenerate();
            $user = User::where('email', $data['loginemail'])->first();
            $request->session()->put('user', $user);
            return redirect()->route('landing');
        } else {
            if (User::where('email', $data['loginemail'])->exists()) {
                // Người dùng đã nhập đúng email nhưng sai mật khẩu
                return redirect()->route('users.showlogin')->with('LoginFailed', 'Invalid password. Please try again.');
            } else {
                // Người dùng đã nhập sai email
                return redirect()->route('users.showlogin')->with('LoginFailed', 'Invalid email. Please try again.');
            }
        }
    }
    public function logout()
    {
        auth()->logout();
        return redirect()->route('landing');
    }
    function showRegister()
    {
        return view('user.signup');
    }
    function updateCurrentBudget(Request $request){
        $data = $request->validate([
            'userid' => ['required'],
            'current_budget_money' => ['numeric']
        ]);
        $user = User::findOrFail($data['userid']);
        $user->current_budget = $data['current_budget_money'];
        $user->save();
        return redirect()->route('budgetCategories.index');
    }
}

resources/views/user/signin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OWedding</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,700;1,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('signin/reset.css') }}">
    <link rel="stylesheet" href="{{ asset('signin/style.css') }}">
</head>
<body>
   <div class="signup">
    <div class="signup__content">
        <h1 class="signup__heading">Login</h1>
        <h2 class="signup__caption">Login with</h2>
        <div class="signup-social">
            <div class="signup-social__item">
                <i class="fab fa-google signup-social__icon"></i>
                <span class="signup-social__text">Login with Google</span>
            </div>
            <div class="signup-social__item">
                <i class="fab fa-facebook signup-social__icon"></i>
                <span class="signup-social__text">Login with Facebook</span>
            </div>
        </div>
        <form class="signup-form" autocomplete="off" method="POST" action="{{ route('users.login') }}">
            @csrf
            <div class="signup-form__row">
                <!-- <div class="signup-form__group">
                    <label for="name" class="signup-form__label">Name</label>
                    <div class="signup-form__validate">

                        <input type="text" class="signup-form__input" id="name" required placeholder="Name">
                        <div class="signup-form__check">
                            <i class="fa fa-check"></i>
                        </div>
                    </div>
                </div> -->
                <div class="signup-form__group">
                    <label for="email" class="signup-form__label">Email</label>
                    <input type="email" class="signup-form__input" id="email" name="loginemail" required placeholder="Email" value="{{ old('loginemail')}}">
                </div>
            </div>
            <div class="signup-form__group">
                <label for="password" class="signup-form__label">Password</label>
                <input type="password" class="signup-form__input" id="password" name="loginpassword" required placeholder="Password">
                @if (session()->has("LoginFailed"))
                <div class="singup-form_passlerr">
                    {{session("LoginFailed")}}
                </div>
                @endif
            </div>
            
            <button class="signup-form__submit" type="submit">
                <i class="fa fa-arrow-right"></i>
            </button>
            <p class="signup__already">Don't have an account? <a href="{{ route('users.showRegister') }}"> Register here!</a></p>
        </form>
    </div>
    <div class="signup__image">
        <img src="/image/Signinimg.png" alt="">
    </div>
   </div>
</body>
</html>

resources/views/user/signup.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OWedding</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,700;1,400&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('signup/reset.css') }}">
    <link rel="stylesheet" href="{{ asset('signup/style.css') }}">
</head>

<body>
    <div class="signup">
        <div class="signup__content">
            <h1 class="signup__heading">Sign Up</h1>
            <h2 class="signup__caption">Sign up with</h2>
            <div class="signup-social">
                <div class="signup-social__item">
                    <i class="fab fa-google signup-social__icon"></i>
                    <span class="signup-social__text">Sign up with Google</span>
                </div>
                <div class="signup-social__item">
                    <i class="fab fa-facebook signup-social__icon"></i>
                    <span class="signup-social__text">Sign up with Facebook</span>
                </div>
            </div>
            <form class="signup-form" autocomplete="off" method="POST" action="{{ route('users.store') }}">
                @csrf
                <div class="signup-form__group">
                    <label for="name" class="signup-form__label">Name</label>
                    <div class="signup-form__validate">
                        <input type="text" class="signup-form__input" id="name" name="name" required
                            placeholder="Name" value="{{ old('name') }}">
                        <div class="signup-form__check">
                            <i class="fa fa-check"></i>
                        </div>
                    </div>
                    @error('name')
                        <div class="signup-form_nameerr">{{ $message }}</div>
                    @enderror
                </div>
                <div class="signup-form__group">
                    <label for="email" class="signup-form__label">Email</label>
                    <input type="email" class="signup-form__input" id="email" name="email" required
                        placeholder="Email" value='{{ old('email') }}'>
                    @error('email')
                        <div class="signup-form_emailerr">{{ $message }}</div>
                    @enderror
                </div>

                <div class="signup-form__row">
                    <div class="signup-form__group">
                        <label for="password" class="signup-form__label">Password</label>
                        <input type="password" class="signup-form__input" id="password" name="password" required
                            placeholder="Password">
                    </div>
                    <div class="signup-form__group">
                        <label for="password" class="signup-form__label">Confirm Password</label>
                        <input type="password" class="signup-form__input" id="password" name="retype_password" required
                            placeholder="Confirm Password">
                    </div>


                    @if ($errors->first('password'))
                        @error('password')
                            <p class="signup-form__row-notmatch">{{ $message }}</p>
                        @enderror
                    @else
                        @error('retype_password')
                            <p class="signup-form__row-notmatch">{{ $message }}</p>
                        @enderror
                    @endif
                </div>
                <!-- <div class="signup-form__term">
                <input type="checkbox" name="" id="term">
                <label for="term">I have read and agree with term</label>
            </div> -->
                <button class="signup-form__submit" type="submit">
                    <i class="fa fa-arrow-right"></i>
                </button>
                <p class="signup__already">Already signin have an account? <a href="{{ route('users.showlogin') }}">Login</a></p>
            </form>
        </div>
        <div class="signup__image">
            <img src="/image/Signinimg.png" alt="">
        </div>
    </div>
</body>

</html>